import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "@/style/font";
import { BottomBar } from "@/components/BottomBar";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-[#F5F5F5]`}
      >
        <Navbar/>
        {children}
        <BottomBar/>
      </body>
    </html>
  );
}
